import { 
  LayoutDashboard, 
  Users, 
  Settings, 
  FolderOpen, 
  BrainCircuit, 
  FileText, 
  Layers, 
  Inbox, 
  Component,
  BookOpen,
  PlayCircle,
  GitPullRequest,
  Building2,
  Dna,
  BotMessageSquare,
  BookMarked,
  Store,
  Radar,
  CircleDollarSign,
  LibraryBig,
  Target,
  UserCog,
  Globe,
  Compass,
  GitMerge
} from 'lucide-react';

export const MAIN_NAVIGATION = [
  { name: 'Orchestrator', href: '/orchestrator', icon: GitMerge },
  { name: 'Atlas Discovery', href: '/discovery', icon: Compass },
  { name: 'Atlas HQ', href: '/command-center', icon: Globe },
  { name: 'Employee Designer', href: '/employee-designer', icon: UserCog },
  { name: 'Business Value', href: '/business-value', icon: Target },
  { name: 'Atlas Framework', href: '/framework', icon: BrainCircuit },
  { name: 'Dental KB', href: '/dental-manager', icon: LibraryBig },
  { name: 'Seguimiento Pptos.', href: '/dental/budgets', icon: Target },
  { name: 'ROI Center', href: '/roi-center', icon: CircleDollarSign },
  { name: 'Inteligencia', href: '/intelligence', icon: Radar },
  { name: 'Marketplace', href: '/marketplace', icon: Store },
  { name: 'Empleados', href: '/employees/demo', icon: BotMessageSquare },
  { name: 'Knowledge Studio', href: '/knowledge-acquisition', icon: BookMarked },
  { name: 'Business DNA', href: '/business-dna', icon: Dna },
  { name: 'Business Studio', href: '/business-studio', icon: Building2 },
  { name: 'Primeros pasos', href: '/onboarding', icon: BookOpen },
  { name: 'Simulador', href: '/simulator', icon: PlayCircle },
  { name: 'Decision Engine', href: '/decision-engine', icon: GitPullRequest },
  { name: 'Panel', href: '/', icon: LayoutDashboard },
  { name: 'Cerebro de Empresa', href: '/brain', icon: BrainCircuit },
  { name: 'Documentos', href: '/documents', icon: FolderOpen },
  { name: 'Equipo', href: '/team', icon: Users },
  { name: 'Ajustes', href: '/settings', icon: Settings },
];

export const BRAIN_NAVIGATION = [
  { name: 'Resumen', href: '', icon: BrainCircuit },
  { name: 'Dominios', href: '/domains', icon: Layers },
  { name: 'Fuentes', href: '/sources', icon: Inbox },
  { name: 'Unidades', href: '/units', icon: Component },
  { name: 'Propuestas', href: '/proposals', icon: FileText },
  { name: 'Ajustes', href: '/settings', icon: Settings },
];
