import { FrameworkEngine } from '../schemas/framework';

export class FrameworkRepository {
  static async getEngines(): Promise<FrameworkEngine[]> {
    // Simulated demo data for the 10 engines
    return [
      {
        id: 'opportunity',
        name: 'Opportunity Engine',
        description: 'Detecta proactivamente oportunidades de negocio no explotadas.',
        status: 'active',
        autonomy: 85,
        confidence: 92,
        evolution: 5,
        explanation: 'Analiza patrones de agenda cruzados con historial de tratamientos.',
      },
      {
        id: 'risk',
        name: 'Risk Engine',
        description: 'Prevé fugas de pacientes, problemas de caja y conflictos de agenda.',
        status: 'active',
        autonomy: 90,
        confidence: 88,
        evolution: 2,
        explanation: 'Modelo predictivo basado en cancelaciones históricas.',
      },
      {
        id: 'recommendation',
        name: 'Recommendation Engine',
        description: 'Sugiere las siguientes mejores acciones para el personal humano.',
        status: 'learning',
        autonomy: 60,
        confidence: 75,
        evolution: 12,
        explanation: 'Motor de inferencia sobre el Knowledge Blueprint.',
      },
      {
        id: 'roi',
        name: 'ROI Engine',
        description: 'Cuantifica en euros cada acción ejecutada por la plataforma.',
        status: 'active',
        autonomy: 100,
        confidence: 98,
        evolution: 1,
        explanation: 'Asigna valor estandarizado a eventos operativos.',
      },
      {
        id: 'confidence',
        name: 'Confidence Engine',
        description: 'Calcula el margen de certeza antes de permitir que Atlas hable.',
        status: 'active',
        autonomy: 100,
        confidence: 100,
        evolution: 0,
        explanation: 'Sistema de scoring de contexto y embeddings.',
      },
      {
        id: 'explainability',
        name: 'Explainability Engine',
        description: 'Visualiza la traza completa de decisiones desde el dato hasta la acción.',
        status: 'active',
        autonomy: 100,
        confidence: 100,
        evolution: 0,
        explanation: 'Log de trazabilidad inmutable.',
      },
      {
        id: 'copilot',
        name: 'Executive Copilot',
        description: 'Tu socio estratégico diario que sintetiza toda la operativa.',
        status: 'active',
        autonomy: 80,
        confidence: 90,
        evolution: 8,
        explanation: 'Agente LLM con contexto macro-financiero.',
      },
      {
        id: 'principles',
        name: 'Atlas Principles',
        description: 'Límites éticos inquebrantables de la inteligencia artificial.',
        status: 'active',
        autonomy: 100,
        confidence: 100,
        evolution: 0,
        explanation: 'Filtro semántico pre-generación.',
      },
      {
        id: 'maturity',
        name: 'Atlas Maturity',
        description: 'Evalúa el nivel de madurez digital y organizativa de la clínica.',
        status: 'learning',
        autonomy: 40,
        confidence: 65,
        evolution: 15,
        explanation: 'Assessment continuo de KPIs y adopción.',
      },
      {
        id: 'decision',
        name: 'Core Decision Engine',
        description: 'El cerebro maestro que orquesta los agentes, políticas y ADN.',
        status: 'active',
        autonomy: 95,
        confidence: 96,
        evolution: 3,
        explanation: 'Motor de reglas determinista + LLM enrutador.',
      }
    ];
  }
}
